# Generated by Django 5.0 on 2023-12-07 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pas_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('x_axis_label', models.CharField(max_length=100)),
                ('y_axis_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticDatapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.statistic')),
            ],
        ),
        migrations.AddField(
            model_name='statistic',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.statistictype'),
        ),
    ]
