# Generated by Django 5.0 on 2023-12-07 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='Analytics.statistictype'),
        ),
        migrations.AlterField(
            model_name='statisticdatapoint',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='Analytics.statistic'),
        ),
    ]
