# Generated by Django 5.0 on 2023-12-07 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_statistic_stat_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', related_query_name='statistic', to='Analytics.statistictype'),
        ),
        migrations.AlterField(
            model_name='statisticdatapoint',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', related_query_name='datapoint', to='Analytics.statistic'),
        ),
    ]
