# Generated by Django 5.0 on 2023-12-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_alter_statistic_stat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='eye',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
