# Generated by Django 5.0 on 2023-12-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_statistic_eye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='eye',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default=None, max_length=1, null=True),
        ),
    ]
