# Generated by Django 4.2.8 on 2023-12-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_alter_statistic_eye'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdatapoint',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
