# Generated by Django 4.2.8 on 2023-12-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0006_statisticdatapoint_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdatapoint',
            name='event_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
