# Generated by Django 4.2.8 on 2023-12-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0007_statisticdatapoint_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='gradient',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='y_intercept',
            field=models.FloatField(null=True),
        ),
    ]
